projects:
  referencebuilder:
    schemaPath: apiwrapper/graphql/schema.json
    includes:
      - apiwrapper/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: apiwrapper/graphql
        maxDepth: 7
extensions:
  amplify:
    version: 3
