projects:
  referencebuildergraphqlv1:
    schemaPath: amplify/backend/api/referencebuildergraphqlv1/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        maxDepth: 6
extensions:
  amplify:
    version: 3
